//! Generated by hexforge-cli. Do not edit manually.

//! ApiKey entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::domain::{PermissionLevel};

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "api_keys")]
pub struct ApiKey {
    #[entity(id)]
    pub id: i64,
    #[crud(required)]
    pub key_hash: String,
    #[crud(required)]
    pub name: String,
    #[crud(required)]
    pub permission: PermissionLevel,
    pub revoked_at: Option<timestamp>,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}

pub fn create_api_key_transform(input: &mut CreateApiKey) {
}

pub fn update_api_key_transform(input: &mut UpdateApiKey) {
}
