//! Generated by hexforge-cli. Do not edit manually.

//! Author entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "authors")]
#[crud(pre_create = "pre_create_author", pre_update = "pre_update_author")]
pub struct Author {
    #[entity(id)]
    pub id: i64,
    #[crud(required)]
    pub author_key: String,
    pub family_name_latex: Option<String>,
    pub family_name_unicode: Option<String>,
    pub famous_name_latex: Option<String>,
    pub famous_name_unicode: Option<String>,
    pub given_name_latex: Option<String>,
    pub given_name_unicode: Option<String>,
    pub mononym_latex: Option<String>,
    pub mononym_unicode: Option<String>,
    pub name_variants: Option<Vec<String>>,
    pub shorthand_latex: Option<String>,
    pub shorthand_unicode: Option<String>,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}

use crate::domain::bib_string_normalize;

fn pre_create_author(input: &mut CreateAuthor) {
    bib_string_normalize(&input.family_name_latex, &mut input.family_name_unicode);
    bib_string_normalize(&input.famous_name_latex, &mut input.famous_name_unicode);
    bib_string_normalize(&input.given_name_latex, &mut input.given_name_unicode);
    bib_string_normalize(&input.mononym_latex, &mut input.mononym_unicode);
    bib_string_normalize(&input.shorthand_latex, &mut input.shorthand_unicode);
}

fn pre_update_author(input: &mut UpdateAuthor) {
    bib_string_normalize(&input.family_name_latex, &mut input.family_name_unicode);
    bib_string_normalize(&input.famous_name_latex, &mut input.famous_name_unicode);
    bib_string_normalize(&input.given_name_latex, &mut input.given_name_unicode);
    bib_string_normalize(&input.mononym_latex, &mut input.mononym_unicode);
    bib_string_normalize(&input.shorthand_latex, &mut input.shorthand_unicode);
}
