//! Generated by hexforge-cli. Do not edit manually.

//! BibItem entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::domain::{EntryType, Epoch, LangId, PubState};

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "bibitems")]
#[crud(pre_create = "pre_create_bib_item", pre_update = "pre_update_bib_item")]
pub struct BibItem {
    #[entity(id)]
    pub id: i64,
    pub address: Option<String>,
    #[crud(required)]
    pub bibkey: String,
    pub booktitle_latex: Option<String>,
    pub booktitle_unicode: Option<String>,
    pub booktitle_simplified: Option<String>,
    pub crossref_id: Option<i64>,
    pub date_day: Option<i16>,
    pub date_is_no_date: bool,
    pub date_month: Option<i16>,
    pub date_year: Option<i16>,
    pub date_year_2_hyphen: Option<i16>,
    pub date_year_2_slash: Option<i16>,
    pub doi: Option<String>,
    pub edition: Option<String>,
    pub eid: Option<String>,
    #[crud(required)]
    pub entry_type: EntryType,
    pub epoch: Option<Epoch>,
    pub eprint: Option<String>,
    pub extra_note_latex: Option<String>,
    pub extra_note_unicode: Option<String>,
    pub fulltext_path: Option<String>,
    pub has_fulltext: bool,
    pub institution_id: Option<i64>,
    pub is_translation: bool,
    pub issuetitle_latex: Option<String>,
    pub issuetitle_unicode: Option<String>,
    pub journal_id: Option<i64>,
    pub langid: Option<LangId>,
    pub note_latex: Option<String>,
    pub note_unicode: Option<String>,
    pub number: Option<String>,
    pub options: Option<String>,
    pub pages: Option<String>,
    pub person_id: Option<i64>,
    pub publisher_id: Option<i64>,
    pub pubstate: Option<PubState>,
    pub school_id: Option<i64>,
    pub series_id: Option<i64>,
    pub shorthand: Option<String>,
    #[crud(required)]
    pub title_latex: String,
    #[crud(required)]
    pub title_unicode: String,
    #[crud(required)]
    pub title_simplified: String,
    pub type_field: Option<String>,
    pub url: Option<String>,
    pub urn: Option<String>,
    pub volume: Option<String>,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}

use crate::domain::{bib_string_normalize, bib_string_normalize_required};

fn pre_create_bib_item(input: &mut CreateBibItem) {
    bib_string_normalize(
        &input.booktitle_latex,
        &mut input.booktitle_unicode,
        &mut input.booktitle_simplified,
    );
    bib_string_normalize_required(
        &input.title_latex,
        &mut input.title_unicode,
        &mut input.title_simplified,
    );
}

fn pre_update_bib_item(input: &mut UpdateBibItem) {
    bib_string_normalize(
        &input.booktitle_latex,
        &mut input.booktitle_unicode,
        &mut input.booktitle_simplified,
    );
    bib_string_normalize(
        &input.title_latex,
        &mut input.title_unicode,
        &mut input.title_simplified,
    );
}
