//! Generated by hexforge-cli. Do not edit manually.

//! BibitemNotes entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "bibitem_notes")]
pub struct BibitemNotes {
    #[entity(id)]
    pub id: i64,
    #[crud(required)]
    pub bibitem_id: i64,
    #[crud(required)]
    pub notes: jsonb,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}

pub fn create_bibitem_notes_transform(input: &mut CreateBibitemNotes) {
}

pub fn update_bibitem_notes_transform(input: &mut UpdateBibitemNotes) {
}
