//! Generated by hexforge-cli. Do not edit manually.

//! BibItem entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};

use crate::domain::{EntryType, Epoch, LangId, PubState};

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize)]
#[entity(table = "bibitems", no_query)]
#[crud(pre_create = "pre_create_bib_item", pre_update = "pre_update_bib_item")]
pub struct BibItem {
    #[entity(id)]
    pub id: i64,
    pub address: Option<String>,
    #[crud(required)]
    pub bibkey: String,
    pub booktitle_latex: Option<String>,
    pub booktitle_unicode: Option<String>,
    pub crossref: Option<String>,
    pub date_day: Option<i16>,
    pub date_is_no_date: bool,
    pub date_month: Option<i16>,
    pub date_year: Option<i16>,
    pub date_year_2_hyphen: Option<i16>,
    pub date_year_2_slash: Option<i16>,
    pub doi: Option<String>,
    pub edition: Option<String>,
    pub eid: Option<String>,
    #[crud(required)]
    pub entry_type: EntryType,
    pub epoch: Option<Epoch>,
    pub eprint: Option<String>,
    pub extra_note_latex: Option<String>,
    pub extra_note_unicode: Option<String>,
    pub fulltext_path: Option<String>,
    pub has_fulltext: bool,
    pub institution_key: Option<String>,
    pub is_translation: bool,
    pub issuetitle_latex: Option<String>,
    pub issuetitle_unicode: Option<String>,
    pub journal_key: Option<String>,
    pub langid: Option<LangId>,
    pub license: Option<String>,
    pub note_latex: Option<String>,
    pub note_unicode: Option<String>,
    pub number: Option<String>,
    pub options: Option<String>,
    pub pages: Option<String>,
    pub person_key: Option<String>,
    pub publisher_key: Option<String>,
    pub pubstate: Option<PubState>,
    pub school_key: Option<String>,
    pub series_key: Option<String>,
    pub shorthand: Option<String>,
    pub start_page: Option<i32>,
    #[crud(required)]
    pub title_latex: String,
    pub title_unicode: Option<String>,
    pub type_field: Option<String>,
    pub url: Option<String>,
    pub urn: Option<String>,
    pub volume: Option<String>,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}

use crate::domain::bib_string_normalize;

fn pre_create_bib_item(input: &mut CreateBibItem) {
    bib_string_normalize(&input.booktitle_latex, &mut input.booktitle_unicode);
}

fn pre_update_bib_item(input: &mut UpdateBibItem) {
    bib_string_normalize(&input.booktitle_latex, &mut input.booktitle_unicode);
}
