//! Generated by hexforge-cli. Do not edit manually.

//! BibitemNotes entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize)]
#[entity(table = "bibitem_notes", no_query)]
pub struct BibitemNotes {
    #[entity(id)]
    pub id: i64,
    #[crud(required)]
    pub bibkey: String,
    pub change_request: Option<String>,
    pub dltc_copyediting_note: Option<String>,
    pub note_missing: Option<String>,
    pub note_perso: Option<String>,
    pub note_stock: Option<String>,
    pub todo_general: Option<String>,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}
