//! Generated by hexforge-cli. Do not edit manually.

//! DataVersion entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "data_version", no_query)]
pub struct DataVersion {
    #[entity(id)]
    pub id: i64,
    pub description: Option<String>,
    #[crud(required)]
    pub imported_at: DateTime<Utc>,
    #[crud(required)]
    pub version: String,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}
