//! Generated by hexforge-cli. Do not edit manually.

//! Domain enums.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

// =============================================================================
// AuthorRole
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AuthorRole {
    #[default]
    Author,
    Editor,
    Guesteditor,
}

impl fmt::Display for AuthorRole {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Author => write!(f, "author"),
            Self::Editor => write!(f, "editor"),
            Self::Guesteditor => write!(f, "guesteditor"),
        }
    }
}

impl FromStr for AuthorRole {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "author" => Ok(Self::Author),
            "editor" => Ok(Self::Editor),
            "guesteditor" => Ok(Self::Guesteditor),
            other => Err(format!("unknown author_role: {other}")),
        }
    }
}

// =============================================================================
// EntryType
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EntryType {
    Article,
    Book,
    Incollection,
    Inproceedings,
    Mastersthesis,
    Misc,
    Phdthesis,
    Proceedings,
    Techreport,
    Unpublished,
    #[default]
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl fmt::Display for EntryType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Article => write!(f, "article"),
            Self::Book => write!(f, "book"),
            Self::Incollection => write!(f, "incollection"),
            Self::Inproceedings => write!(f, "inproceedings"),
            Self::Mastersthesis => write!(f, "mastersthesis"),
            Self::Misc => write!(f, "misc"),
            Self::Phdthesis => write!(f, "phdthesis"),
            Self::Proceedings => write!(f, "proceedings"),
            Self::Techreport => write!(f, "techreport"),
            Self::Unpublished => write!(f, "unpublished"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl FromStr for EntryType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "article" => Ok(Self::Article),
            "book" => Ok(Self::Book),
            "incollection" => Ok(Self::Incollection),
            "inproceedings" => Ok(Self::Inproceedings),
            "mastersthesis" => Ok(Self::Mastersthesis),
            "misc" => Ok(Self::Misc),
            "phdthesis" => Ok(Self::Phdthesis),
            "proceedings" => Ok(Self::Proceedings),
            "techreport" => Ok(Self::Techreport),
            "unpublished" => Ok(Self::Unpublished),
            "UNKNOWN" => Ok(Self::Unknown),
            other => Err(format!("unknown entry_type: {other}")),
        }
    }
}

// =============================================================================
// Epoch
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Epoch {
    AncientPhilosophy,
    AncientScientists,
    AustrianPhilosophy,
    BritishIdealism,
    Classics,
    Contemporaries,
    ContemporaryScientists,
    ContinentalPhilosophy,
    CriticalTheory,
    Cynics,
    Enlightenment,
    Existentialism,
    ExoticPhilosophy,
    GermanIdealism,
    GermanRationalism,
    GestaltPsychology,
    Hermeneutics,
    IslamicPhilosophy,
    Mathematicians,
    MedievalPhilosophy,
    ModernPhilosophy,
    ModernScientists,
    NeoKantianism,
    Neoplatonism,
    NewRealism,
    OrdinaryLanguagePhilosophy,
    Phenomenology,
    PolishLogic,
    Pragmatism,
    Presocratics,
    Renaissance,
    Stoics,
    Theologians,
    ViennaCircle,
}

impl fmt::Display for Epoch {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AncientPhilosophy => write!(f, "ancient-philosophy"),
            Self::AncientScientists => write!(f, "ancient-scientists"),
            Self::AustrianPhilosophy => write!(f, "austrian-philosophy"),
            Self::BritishIdealism => write!(f, "british-idealism"),
            Self::Classics => write!(f, "classics"),
            Self::Contemporaries => write!(f, "contemporaries"),
            Self::ContemporaryScientists => write!(f, "contemporary-scientists"),
            Self::ContinentalPhilosophy => write!(f, "continental-philosophy"),
            Self::CriticalTheory => write!(f, "critical-theory"),
            Self::Cynics => write!(f, "cynics"),
            Self::Enlightenment => write!(f, "enlightenment"),
            Self::Existentialism => write!(f, "existentialism"),
            Self::ExoticPhilosophy => write!(f, "exotic-philosophy"),
            Self::GermanIdealism => write!(f, "german-idealism"),
            Self::GermanRationalism => write!(f, "german-rationalism"),
            Self::GestaltPsychology => write!(f, "gestalt-psychology"),
            Self::Hermeneutics => write!(f, "hermeneutics"),
            Self::IslamicPhilosophy => write!(f, "islamic-philosophy"),
            Self::Mathematicians => write!(f, "mathematicians"),
            Self::MedievalPhilosophy => write!(f, "medieval-philosophy"),
            Self::ModernPhilosophy => write!(f, "modern-philosophy"),
            Self::ModernScientists => write!(f, "modern-scientists"),
            Self::NeoKantianism => write!(f, "neo-kantianism"),
            Self::Neoplatonism => write!(f, "neoplatonism"),
            Self::NewRealism => write!(f, "new-realism"),
            Self::OrdinaryLanguagePhilosophy => write!(f, "ordinary-language-philosophy"),
            Self::Phenomenology => write!(f, "phenomenology"),
            Self::PolishLogic => write!(f, "polish-logic"),
            Self::Pragmatism => write!(f, "pragmatism"),
            Self::Presocratics => write!(f, "presocratics"),
            Self::Renaissance => write!(f, "renaissance"),
            Self::Stoics => write!(f, "stoics"),
            Self::Theologians => write!(f, "theologians"),
            Self::ViennaCircle => write!(f, "vienna-circle"),
        }
    }
}

impl FromStr for Epoch {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "ancient-philosophy" => Ok(Self::AncientPhilosophy),
            "ancient-scientists" => Ok(Self::AncientScientists),
            "austrian-philosophy" => Ok(Self::AustrianPhilosophy),
            "british-idealism" => Ok(Self::BritishIdealism),
            "classics" => Ok(Self::Classics),
            "contemporaries" => Ok(Self::Contemporaries),
            "contemporary-scientists" => Ok(Self::ContemporaryScientists),
            "continental-philosophy" => Ok(Self::ContinentalPhilosophy),
            "critical-theory" => Ok(Self::CriticalTheory),
            "cynics" => Ok(Self::Cynics),
            "enlightenment" => Ok(Self::Enlightenment),
            "existentialism" => Ok(Self::Existentialism),
            "exotic-philosophy" => Ok(Self::ExoticPhilosophy),
            "german-idealism" => Ok(Self::GermanIdealism),
            "german-rationalism" => Ok(Self::GermanRationalism),
            "gestalt-psychology" => Ok(Self::GestaltPsychology),
            "hermeneutics" => Ok(Self::Hermeneutics),
            "islamic-philosophy" => Ok(Self::IslamicPhilosophy),
            "mathematicians" => Ok(Self::Mathematicians),
            "medieval-philosophy" => Ok(Self::MedievalPhilosophy),
            "modern-philosophy" => Ok(Self::ModernPhilosophy),
            "modern-scientists" => Ok(Self::ModernScientists),
            "neo-kantianism" => Ok(Self::NeoKantianism),
            "neoplatonism" => Ok(Self::Neoplatonism),
            "new-realism" => Ok(Self::NewRealism),
            "ordinary-language-philosophy" => Ok(Self::OrdinaryLanguagePhilosophy),
            "phenomenology" => Ok(Self::Phenomenology),
            "polish-logic" => Ok(Self::PolishLogic),
            "pragmatism" => Ok(Self::Pragmatism),
            "presocratics" => Ok(Self::Presocratics),
            "renaissance" => Ok(Self::Renaissance),
            "stoics" => Ok(Self::Stoics),
            "theologians" => Ok(Self::Theologians),
            "vienna-circle" => Ok(Self::ViennaCircle),
            other => Err(format!("unknown epoch: {other}")),
        }
    }
}

// =============================================================================
// LangId
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LangId {
    Catalan,
    Czech,
    Danish,
    Dutch,
    English,
    French,
    German,
    Greek,
    Italian,
    Latin,
    Lithuanian,
    Polish,
    Portuguese,
    Romanian,
    Russian,
    Slovak,
    Spanish,
    Swedish,
    Unknown,
}

impl fmt::Display for LangId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Catalan => write!(f, "catalan"),
            Self::Czech => write!(f, "czech"),
            Self::Danish => write!(f, "danish"),
            Self::Dutch => write!(f, "dutch"),
            Self::English => write!(f, "english"),
            Self::French => write!(f, "french"),
            Self::German => write!(f, "german"),
            Self::Greek => write!(f, "greek"),
            Self::Italian => write!(f, "italian"),
            Self::Latin => write!(f, "latin"),
            Self::Lithuanian => write!(f, "lithuanian"),
            Self::Polish => write!(f, "polish"),
            Self::Portuguese => write!(f, "portuguese"),
            Self::Romanian => write!(f, "romanian"),
            Self::Russian => write!(f, "russian"),
            Self::Slovak => write!(f, "slovak"),
            Self::Spanish => write!(f, "spanish"),
            Self::Swedish => write!(f, "swedish"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

impl FromStr for LangId {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "catalan" => Ok(Self::Catalan),
            "czech" => Ok(Self::Czech),
            "danish" => Ok(Self::Danish),
            "dutch" => Ok(Self::Dutch),
            "english" => Ok(Self::English),
            "french" => Ok(Self::French),
            "german" => Ok(Self::German),
            "greek" => Ok(Self::Greek),
            "italian" => Ok(Self::Italian),
            "latin" => Ok(Self::Latin),
            "lithuanian" => Ok(Self::Lithuanian),
            "polish" => Ok(Self::Polish),
            "portuguese" => Ok(Self::Portuguese),
            "romanian" => Ok(Self::Romanian),
            "russian" => Ok(Self::Russian),
            "slovak" => Ok(Self::Slovak),
            "spanish" => Ok(Self::Spanish),
            "swedish" => Ok(Self::Swedish),
            "unknown" => Ok(Self::Unknown),
            other => Err(format!("unknown lang_id: {other}")),
        }
    }
}

// =============================================================================
// License
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum License {
    #[serde(rename = "cc-by-3")]
    CcBy3,
    #[serde(rename = "cc-by-4")]
    CcBy4,
    #[serde(rename = "cc-by-sa-3")]
    CcBySa3,
    #[serde(rename = "cc-by-sa-4")]
    CcBySa4,
    #[serde(rename = "cc-by-nc-3")]
    CcByNc3,
    #[serde(rename = "cc-by-nc-4")]
    CcByNc4,
    #[serde(rename = "cc-by-nc-sa-3")]
    CcByNcSa3,
    #[serde(rename = "cc-by-nc-sa-4")]
    CcByNcSa4,
    #[serde(rename = "cc-by-nd-4")]
    CcByNd4,
    #[serde(rename = "cc-by-nc-nd-4")]
    CcByNcNd4,
    Cc0,
    AllRightsReserved,
}

impl fmt::Display for License {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::CcBy3 => write!(f, "cc-by-3"),
            Self::CcBy4 => write!(f, "cc-by-4"),
            Self::CcBySa3 => write!(f, "cc-by-sa-3"),
            Self::CcBySa4 => write!(f, "cc-by-sa-4"),
            Self::CcByNc3 => write!(f, "cc-by-nc-3"),
            Self::CcByNc4 => write!(f, "cc-by-nc-4"),
            Self::CcByNcSa3 => write!(f, "cc-by-nc-sa-3"),
            Self::CcByNcSa4 => write!(f, "cc-by-nc-sa-4"),
            Self::CcByNd4 => write!(f, "cc-by-nd-4"),
            Self::CcByNcNd4 => write!(f, "cc-by-nc-nd-4"),
            Self::Cc0 => write!(f, "cc0"),
            Self::AllRightsReserved => write!(f, "all-rights-reserved"),
        }
    }
}

impl FromStr for License {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "cc-by-3" => Ok(Self::CcBy3),
            "cc-by-4" => Ok(Self::CcBy4),
            "cc-by-sa-3" => Ok(Self::CcBySa3),
            "cc-by-sa-4" => Ok(Self::CcBySa4),
            "cc-by-nc-3" => Ok(Self::CcByNc3),
            "cc-by-nc-4" => Ok(Self::CcByNc4),
            "cc-by-nc-sa-3" => Ok(Self::CcByNcSa3),
            "cc-by-nc-sa-4" => Ok(Self::CcByNcSa4),
            "cc-by-nd-4" => Ok(Self::CcByNd4),
            "cc-by-nc-nd-4" => Ok(Self::CcByNcNd4),
            "cc0" => Ok(Self::Cc0),
            "all-rights-reserved" => Ok(Self::AllRightsReserved),
            other => Err(format!("unknown license: {other}")),
        }
    }
}

// =============================================================================
// PermissionLevel
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PermissionLevel {
    Public,
    #[default]
    Read,
    Write,
    Admin,
}

impl fmt::Display for PermissionLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Public => write!(f, "public"),
            Self::Read => write!(f, "read"),
            Self::Write => write!(f, "write"),
            Self::Admin => write!(f, "admin"),
        }
    }
}

impl FromStr for PermissionLevel {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "public" => Ok(Self::Public),
            "read" => Ok(Self::Read),
            "write" => Ok(Self::Write),
            "admin" => Ok(Self::Admin),
            other => Err(format!("unknown permission_level: {other}")),
        }
    }
}

// =============================================================================
// PubState
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PubState {
    Unpub,
    Forthcoming,
    Inwork,
    Submitted,
    Published,
}

impl fmt::Display for PubState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unpub => write!(f, "unpub"),
            Self::Forthcoming => write!(f, "forthcoming"),
            Self::Inwork => write!(f, "inwork"),
            Self::Submitted => write!(f, "submitted"),
            Self::Published => write!(f, "published"),
        }
    }
}

impl FromStr for PubState {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "unpub" => Ok(Self::Unpub),
            "forthcoming" => Ok(Self::Forthcoming),
            "inwork" => Ok(Self::Inwork),
            "submitted" => Ok(Self::Submitted),
            "published" => Ok(Self::Published),
            other => Err(format!("unknown pub_state: {other}")),
        }
    }
}

// =============================================================================
// RefType
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RefType {
    FurtherRef,
    DependsOn,
}

impl fmt::Display for RefType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::FurtherRef => write!(f, "further_ref"),
            Self::DependsOn => write!(f, "depends_on"),
        }
    }
}

impl FromStr for RefType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "further_ref" => Ok(Self::FurtherRef),
            "depends_on" => Ok(Self::DependsOn),
            other => Err(format!("unknown ref_type: {other}")),
        }
    }
}
