//! Generated by hexforge-cli. Do not edit manually.

//! Institution entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "institutions")]
pub struct Institution {
    #[entity(id)]
    pub id: i64,
    pub default_address: Option<String>,
    #[crud(required)]
    pub institution_key: String,
    #[crud(required)]
    pub name_latex: String,
    #[crud(required)]
    pub name_unicode: String,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}
