//! Generated by hexforge-cli. Do not edit manually.

//! Journal entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "journals", no_query)]
pub struct Journal {
    #[entity(id)]
    pub id: i64,
    pub issn_electronic: Option<String>,
    pub issn_print: Option<String>,
    #[crud(required)]
    pub journal_key: String,
    #[crud(required)]
    pub name_latex: String,
    #[crud(required)]
    pub name_unicode: String,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}
