//! Generated by hexforge-cli. Do not edit manually.

//! Junction table row types.

use crate::domain::{AuthorRole, RefType};
use hexforge::db_exports::FromRow;

#[derive(Debug, Clone, FromRow)]
pub struct BibitemAuthorsRow {
    pub bibkey: String,
    pub author_key: String,
    pub role: AuthorRole,
    pub position: i16,
    pub name_variant_latex: Option<String>,
    pub name_variant_unicode: Option<String>,
}

#[derive(Debug, Clone, FromRow)]
pub struct BibitemDependsOnRow {
    pub source_key: String,
    pub dep_key: String,
}

#[derive(Debug, Clone, FromRow)]
pub struct BibitemFurtherRefsRow {
    pub source_key: String,
    pub dep_key: String,
}

#[derive(Debug, Clone, FromRow)]
pub struct BibitemKeywordsRow {
    pub bibkey: String,
    pub keyword_key: String,
    pub keyword_level: i16,
}

#[derive(Debug, Clone, FromRow)]
pub struct BibitemRefsRow {
    pub source_key: String,
    pub target_key: String,
    pub ref_type: RefType,
}
