//! Generated by hexforge-cli. Do not edit manually.

//! Junction table row types.

use hexforge::db_exports::FromRow;

#[derive(Debug, Clone, FromRow)]
pub struct BibitemAuthorsRow {
    pub bibitem_id: i64,
    pub author_id: i64,
    pub role: String,
    pub position: i16,
    pub name_variant_latex: Option<String>,
    pub name_variant_unicode: Option<String>,
}

#[derive(Debug, Clone, FromRow)]
pub struct BibitemKeywordsRow {
    pub bibitem_id: i64,
    pub keyword_id: i64,
    pub keyword_level: i16,
}

#[derive(Debug, Clone, FromRow)]
pub struct BibitemRefsRow {
    pub source_id: i64,
    pub target_id: i64,
    pub ref_type: String,
}
