//! Generated by hexforge-cli. Do not edit manually.

//! Keyword entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "keywords")]
pub struct Keyword {
    #[entity(id)]
    pub id: i64,
    #[crud(required)]
    pub keyword_key: String,
    #[crud(required)]
    pub level: i16,
    #[crud(required)]
    pub name: String,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}
