//! Generated by hexforge-cli. Do not edit manually.

//! Projections -- typed field subsets for list, search, and expansion views.

use hexforge::Projection;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use super::{
    Author, BibItem, EntryType, Institution, Journal, Keyword, PubState, Publisher, School, Series,
};

/// summary projection of [`BibItem`] for `?view=summary` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "BibItem")]
pub struct BibItemSummary {
    pub id: i64,
    pub bibkey: String,
    pub entry_type: EntryType,
    pub title_unicode: String,
    pub date_year: Option<i16>,
    pub pubstate: Option<PubState>,
}

/// Expanded projection of [`Author`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "Author")]
pub struct AuthorExpanded {
    pub id: i64,
    pub author_key: String,
    pub given_name_unicode: Option<String>,
    pub family_name_unicode: Option<String>,
    pub mononym_unicode: Option<String>,
}

/// Expanded projection of [`BibItem`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "BibItem")]
pub struct BibItemCrossref {
    pub id: i64,
    pub bibkey: String,
    pub entry_type: EntryType,
    pub title_unicode: String,
    pub date_year: Option<i16>,
}

/// Expanded projection of [`Institution`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "Institution")]
pub struct InstitutionExpanded {
    pub id: i64,
    pub institution_key: String,
    pub name_unicode: String,
}

/// Expanded projection of [`Journal`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "Journal")]
pub struct JournalExpanded {
    pub id: i64,
    pub journal_key: String,
    pub name_unicode: String,
}

/// Expanded projection of [`Keyword`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "Keyword")]
pub struct KeywordExpanded {
    pub id: i64,
    pub name: String,
    pub level: i16,
}

/// Expanded projection of [`Publisher`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "Publisher")]
pub struct PublisherExpanded {
    pub id: i64,
    pub publisher_key: String,
    pub name_unicode: String,
}

/// Expanded projection of [`School`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "School")]
pub struct SchoolExpanded {
    pub id: i64,
    pub school_key: String,
    pub name_unicode: String,
}

/// Expanded projection of [`Series`] for `?expand=` responses.
#[derive(Projection, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[projection(entity = "Series")]
pub struct SeriesExpanded {
    pub id: i64,
    pub series_key: String,
    pub name_unicode: String,
}
