//! Generated by hexforge-cli. Do not edit manually.

//! School entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize)]
#[entity(table = "schools", no_query)]
pub struct School {
    #[entity(id)]
    pub id: i64,
    #[crud(required)]
    pub name_latex: String,
    #[crud(required)]
    pub name_unicode: String,
    #[crud(required)]
    pub school_key: String,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}
