//! Generated by hexforge-cli. Do not edit manually.

//! Series entity.

use chrono::{DateTime, Utc};
use hexforge::{Crud, Entity};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Entity, Crud, Clone, Debug, Serialize, Deserialize, ToSchema)]
#[entity(table = "series")]
pub struct Series {
    #[entity(id)]
    pub id: i64,
    #[crud(required)]
    pub name_latex: String,
    #[crud(required)]
    pub name_simplified: String,
    #[crud(required)]
    pub name_unicode: String,
    #[crud(required)]
    pub series_key: String,
    #[crud(skip)]
    pub created_at: DateTime<Utc>,
    #[crud(skip)]
    pub updated_at: DateTime<Utc>,
}
