//! Generated by hexforge-cli. Do not edit manually.

//! Application state -- holds all data sources and shared resources.

use hexforge::{DataStore, DatabasePool};

use crate::adapters::db::queries::{
    ApiKeyQuery, AuthorQuery, BibItemQuery, BibitemNotesQuery, DataVersionQuery, InstitutionQuery,
    JournalQuery, KeywordQuery, PublisherQuery, SchoolQuery, SeriesQuery,
};
use crate::domain::{
    ApiKey, Author, BibItem, BibitemNotes, DataVersion, Institution, Journal, Keyword, Publisher,
    School, Series,
};

#[derive(Clone)]
pub struct AppState {
    pub pool: DatabasePool,
    pub api_key_ds: DataStore<ApiKey, ApiKeyQuery>,
    pub author_ds: DataStore<Author, AuthorQuery>,
    pub bibitem_ds: DataStore<BibItem, BibItemQuery>,
    pub bibitem_notes_ds: DataStore<BibitemNotes, BibitemNotesQuery>,
    pub data_version_ds: DataStore<DataVersion, DataVersionQuery>,
    pub institution_ds: DataStore<Institution, InstitutionQuery>,
    pub journal_ds: DataStore<Journal, JournalQuery>,
    pub keyword_ds: DataStore<Keyword, KeywordQuery>,
    pub publisher_ds: DataStore<Publisher, PublisherQuery>,
    pub school_ds: DataStore<School, SchoolQuery>,
    pub series_ds: DataStore<Series, SeriesQuery>,
}

impl AppState {
    pub fn new(pool: DatabasePool) -> Self {
        let api_key_ds = DataStore::new(pool.clone());
        let author_ds = DataStore::new(pool.clone());
        let bibitem_ds = DataStore::new(pool.clone());
        let bibitem_notes_ds = DataStore::new(pool.clone());
        let data_version_ds = DataStore::new(pool.clone());
        let institution_ds = DataStore::new(pool.clone());
        let journal_ds = DataStore::new(pool.clone());
        let keyword_ds = DataStore::new(pool.clone());
        let publisher_ds = DataStore::new(pool.clone());
        let school_ds = DataStore::new(pool.clone());
        let series_ds = DataStore::new(pool.clone());

        Self {
            pool,
            api_key_ds,
            author_ds,
            bibitem_ds,
            bibitem_notes_ds,
            data_version_ds,
            institution_ds,
            journal_ds,
            keyword_ds,
            publisher_ds,
            school_ds,
            series_ds,
        }
    }
}
