//! Generated by hexforge-cli. Do not edit manually.

//! OpenAPI schema implementations for domain types.

use hexforge::impl_to_schema;

impl_to_schema! {
    struct crate::domain::ApiKey => "ApiKey" {
        id: i64,
        key_hash: String,
        name: String,
        permission: crate::domain::PermissionLevel,
        revoked_at: Option<String>,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::Author => "Author" {
        id: i64,
        author_key: String,
        family_name_latex: Option<String>,
        family_name_unicode: Option<String>,
        famous: bool,
        famous_name_latex: Option<String>,
        famous_name_unicode: Option<String>,
        given_name_latex: Option<String>,
        given_name_unicode: Option<String>,
        mononym_latex: Option<String>,
        mononym_unicode: Option<String>,
        name_variants_latex: Option<Vec<String>>,
        name_variants_unicode: Option<Vec<String>>,
        shorthand_latex: Option<String>,
        shorthand_unicode: Option<String>,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::BibItem => "BibItem" {
        id: i64,
        address: Option<String>,
        bibkey: String,
        booktitle_latex: Option<String>,
        booktitle_unicode: Option<String>,
        crossref: Option<String>,
        date_day: Option<i16>,
        date_is_no_date: bool,
        date_month: Option<i16>,
        date_year: Option<i16>,
        date_year_2_hyphen: Option<i16>,
        date_year_2_slash: Option<i16>,
        doi: Option<String>,
        edition: Option<String>,
        eid: Option<String>,
        entry_type: crate::domain::EntryType,
        epoch: Option<crate::domain::Epoch>,
        eprint: Option<String>,
        extra_note_latex: Option<String>,
        extra_note_unicode: Option<String>,
        fulltext_path: Option<String>,
        has_fulltext: bool,
        institution_key: Option<String>,
        is_translation: bool,
        issuetitle_latex: Option<String>,
        issuetitle_unicode: Option<String>,
        journal_key: Option<String>,
        langid: Option<crate::domain::LangId>,
        note_latex: Option<String>,
        note_unicode: Option<String>,
        number: Option<String>,
        options: Option<String>,
        pages: Option<String>,
        person_key: Option<String>,
        publisher_key: Option<String>,
        pubstate: Option<crate::domain::PubState>,
        school_key: Option<String>,
        series_key: Option<String>,
        shorthand: Option<String>,
        title_latex: String,
        title_unicode: Option<String>,
        type_field: Option<String>,
        url: Option<String>,
        urn: Option<String>,
        volume: Option<String>,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::BibitemNotes => "BibitemNotes" {
        id: i64,
        bibkey: String,
        change_request: Option<String>,
        dltc_copyediting_note: Option<String>,
        note_missing: Option<String>,
        note_perso: Option<String>,
        note_stock: Option<String>,
        todo_general: Option<String>,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::DataVersion => "DataVersion" {
        id: i64,
        description: Option<String>,
        imported_at: String,
        version: String,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::Institution => "Institution" {
        id: i64,
        default_address: Option<String>,
        institution_key: String,
        name_latex: String,
        name_unicode: String,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::Journal => "Journal" {
        id: i64,
        issn_electronic: Option<String>,
        issn_print: Option<String>,
        journal_key: String,
        name_latex: String,
        name_unicode: String,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::Keyword => "Keyword" {
        id: i64,
        keyword_key: String,
        level: i16,
        name: String,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::Publisher => "Publisher" {
        id: i64,
        default_address: Option<String>,
        name_latex: String,
        name_unicode: String,
        publisher_key: String,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::School => "School" {
        id: i64,
        name_latex: String,
        name_unicode: String,
        school_key: String,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    struct crate::domain::Series => "Series" {
        id: i64,
        name_latex: String,
        name_unicode: String,
        series_key: String,
        created_at: String,
        updated_at: String,
    }
}

impl_to_schema! {
    crate::domain::AuthorRole => "AuthorRole", rename_all = "lowercase" {
        Author,
        Editor,
        Guesteditor,
    }
}

impl_to_schema! {
    crate::domain::EntryType => "EntryType", rename_all = "lowercase" {
        Article,
        Book,
        Incollection,
        Inproceedings,
        Mastersthesis,
        Misc,
        Phdthesis,
        Proceedings,
        Techreport,
        Unpublished,
        Unknown = "UNKNOWN",
    }
}

impl_to_schema! {
    crate::domain::Epoch => "Epoch", rename_all = "kebab-case" {
        AncientPhilosophy,
        AncientScientists,
        AustrianPhilosophy,
        BritishIdealism,
        Classics,
        Contemporaries,
        ContemporaryScientists,
        ContinentalPhilosophy,
        CriticalTheory,
        Cynics,
        Enlightenment,
        Existentialism,
        ExoticPhilosophy,
        GermanIdealism,
        GermanRationalism,
        GestaltPsychology,
        Hermeneutics,
        IslamicPhilosophy,
        Mathematicians,
        MedievalPhilosophy,
        ModernPhilosophy,
        ModernScientists,
        NeoKantianism,
        Neoplatonism,
        NewRealism,
        OrdinaryLanguagePhilosophy,
        Phenomenology,
        PolishLogic,
        Pragmatism,
        Presocratics,
        Renaissance,
        Stoics,
        Theologians,
        ViennaCircle,
    }
}

impl_to_schema! {
    crate::domain::LangId => "LangId", rename_all = "lowercase" {
        Catalan,
        Czech,
        Danish,
        Dutch,
        English,
        French,
        Greek,
        Italian,
        Latin,
        Lithuanian,
        Ngerman,
        Polish,
        Portuguese,
        Romanian,
        Russian,
        Slovak,
        Spanish,
        Swedish,
        Unknown,
    }
}

impl_to_schema! {
    crate::domain::PermissionLevel => "PermissionLevel", rename_all = "lowercase" {
        Public,
        Read,
        Write,
        Admin,
    }
}

impl_to_schema! {
    crate::domain::PubState => "PubState", rename_all = "lowercase" {
        Unpub,
        Forthcoming,
        Inwork,
        Submitted,
        Published,
    }
}

impl_to_schema! {
    crate::domain::RefType => "RefType", rename_all = "snake_case" {
        FurtherRef,
        DependsOn,
    }
}

impl_to_schema! {
    struct crate::domain::projections::BibItemSummary => "BibItemSummary" {
        id: i64,
        bibkey: String,
        entry_type: crate::domain::EntryType,
        title_unicode: Option<String>,
        date_year: Option<i16>,
        pubstate: Option<crate::domain::PubState>,
    }
}

impl_to_schema! {
    struct crate::domain::projections::AuthorExpanded => "AuthorExpanded" {
        id: i64,
        author_key: String,
        given_name_unicode: Option<String>,
        family_name_unicode: Option<String>,
        mononym_unicode: Option<String>,
    }
}

impl_to_schema! {
    struct crate::domain::projections::BibItemCrossref => "BibItemCrossref" {
        id: i64,
        bibkey: String,
        entry_type: crate::domain::EntryType,
        title_unicode: Option<String>,
        date_year: Option<i16>,
    }
}

impl_to_schema! {
    struct crate::domain::projections::InstitutionExpanded => "InstitutionExpanded" {
        id: i64,
        institution_key: String,
        name_unicode: String,
    }
}

impl_to_schema! {
    struct crate::domain::projections::JournalExpanded => "JournalExpanded" {
        id: i64,
        journal_key: String,
        name_unicode: String,
    }
}

impl_to_schema! {
    struct crate::domain::projections::KeywordExpanded => "KeywordExpanded" {
        id: i64,
        keyword_key: String,
        name: String,
        level: i16,
    }
}

impl_to_schema! {
    struct crate::domain::projections::PublisherExpanded => "PublisherExpanded" {
        id: i64,
        publisher_key: String,
        name_unicode: String,
    }
}

impl_to_schema! {
    struct crate::domain::projections::SchoolExpanded => "SchoolExpanded" {
        id: i64,
        school_key: String,
        name_unicode: String,
    }
}

impl_to_schema! {
    struct crate::domain::projections::SeriesExpanded => "SeriesExpanded" {
        id: i64,
        series_key: String,
        name_unicode: String,
    }
}
