//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for api_key.

use hexforge::Filter;
use serde::Deserialize;

/// Query parameters for filtering api_key results.
#[derive(Filter, Debug, Default, Deserialize)]
pub struct ApiKeyQuery {}
