//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for api_key.

use hexforge::Filter;
use serde::Deserialize;

#[derive(Filter, Debug, Default, Deserialize)]
pub struct ApiKeyQuery {
}
