//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for author.

use hexforge::Filter;
use serde::Deserialize;

/// Query parameters for filtering author results.
///
/// Supported filters:
/// - `family_name` — LIKE on `family_name_unicode`
/// - `search_term` — LIKE across `family_name_unicode,given_name_unicode`
#[derive(Filter, Debug, Default, Deserialize)]
pub struct AuthorQuery {
    #[query(like = "family_name_unicode")]
    pub family_name: Option<String>,
    #[query(like_any = "family_name_unicode,given_name_unicode")]
    pub search_term: Option<String>,
}
