//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for bib_item.

use hexforge::Filter;
use serde::Deserialize;

#[derive(Filter, Debug, Default, Deserialize)]
pub struct BibItemQuery {
    #[query(raw = "id IN (SELECT bibitem_id FROM bibitem_authors WHERE author_id = $)")]
    pub author_id: Option<i64>,
    #[query(eq_cast = "entry_type::entry_type")]
    pub entry_type: Option<String>,
    #[query(eq_cast = "epoch::epoch")]
    pub epoch: Option<String>,
    #[query(eq = "journal_id")]
    pub journal_id: Option<i64>,
    #[query(like = "title_simplified")]
    pub search_term: Option<String>,
    #[query(gte = "date_year")]
    pub year_from: Option<i16>,
    #[query(lte = "date_year")]
    pub year_to: Option<i16>,
}
