//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for bibitem_notes.

use hexforge::Filter;
use serde::Deserialize;

#[derive(Filter, Debug, Default, Deserialize)]
pub struct BibitemNotesQuery {
}
