//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for bib_item.

use hexforge::Filter;
use serde::Deserialize;

/// Query parameters for filtering bib_item results.
///
/// Supported filters:
/// - `author_key` — raw SQL filter
/// - `entry_type` — exact match on `entry_type::entry_type`
/// - `epoch` — exact match on `epoch::epoch`
/// - `journal_key` — exact match on `journal_key`
/// - `search_term` — LIKE on `title_unicode`
/// - `year_from` — >= on `date_year`
/// - `year_to` — <= on `date_year`
#[derive(Filter, Debug, Default, Deserialize)]
pub struct BibItemQuery {
    #[query(raw = "bibkey IN (SELECT bibkey FROM bibitem_authors WHERE author_key = $)")]
    pub author_key: Option<String>,
    #[query(eq_cast = "entry_type::entry_type")]
    pub entry_type: Option<String>,
    #[query(eq_cast = "epoch::epoch")]
    pub epoch: Option<String>,
    #[query(eq = "journal_key")]
    pub journal_key: Option<String>,
    #[query(like = "title_unicode")]
    pub search_term: Option<String>,
    #[query(gte = "date_year")]
    pub year_from: Option<i16>,
    #[query(lte = "date_year")]
    pub year_to: Option<i16>,
}
