//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for data_version.

use hexforge::Filter;
use serde::Deserialize;

/// Query parameters for filtering data_version results.
#[derive(Filter, Debug, Default, Deserialize)]
pub struct DataVersionQuery {}
