//! Generated by hexforge-cli. Do not edit manually.

//! Junction table batch-fetch functions.

use hexforge::HexforgeError;
use hexforge::db_exports::{PgPool, query_as};

use crate::domain::junctions::*;

pub async fn fetch_bibitem_authors_batch(
    pool: &PgPool,
    ids: &[i64],
) -> Result<Vec<BibitemAuthorsRow>, HexforgeError> {
    query_as::<_, BibitemAuthorsRow>(
        "SELECT bibitem_id, author_id, role::text as role, position, name_variant_latex, name_variant_unicode FROM bibitem_authors WHERE bibitem_id = ANY($1) ORDER BY bibitem_id, role, position"
    )
    .bind(ids)
    .fetch_all(pool)
    .await
    .map_err(HexforgeError::data_source)
}

pub async fn fetch_bibitem_keywords_batch(
    pool: &PgPool,
    ids: &[i64],
) -> Result<Vec<BibitemKeywordsRow>, HexforgeError> {
    query_as::<_, BibitemKeywordsRow>(
        "SELECT bibitem_id, keyword_id, keyword_level FROM bibitem_keywords WHERE bibitem_id = ANY($1) ORDER BY bibitem_id"
    )
    .bind(ids)
    .fetch_all(pool)
    .await
    .map_err(HexforgeError::data_source)
}

pub async fn fetch_bibitem_refs_batch(
    pool: &PgPool,
    ids: &[i64],
) -> Result<Vec<BibitemRefsRow>, HexforgeError> {
    query_as::<_, BibitemRefsRow>(
        "SELECT source_id, target_id, ref_type::text as ref_type FROM bibitem_refs WHERE source_id = ANY($1) ORDER BY source_id, ref_type"
    )
    .bind(ids)
    .fetch_all(pool)
    .await
    .map_err(HexforgeError::data_source)
}
