//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for keyword.

use hexforge::Filter;
use serde::Deserialize;

/// Query parameters for filtering keyword results.
///
/// Supported filters:
/// - `level` — exact match on `level`
/// - `name` — LIKE on `name`
#[derive(Filter, Debug, Default, Deserialize)]
pub struct KeywordQuery {
    #[query(eq = "level")]
    pub level: Option<i64>,
    #[query(like = "name")]
    pub name: Option<String>,
}
