//! Generated by hexforge-cli. Do not edit manually.

//! Query filter for publisher.

use hexforge::Filter;
use serde::Deserialize;

/// Query parameters for filtering publisher results.
///
/// Supported filters:
/// - `name` — LIKE on `name_simplified`
#[derive(Filter, Debug, Default, Deserialize)]
pub struct PublisherQuery {
    #[query(like = "name_simplified")]
    pub name: Option<String>,
}
