//! Generated by hexforge-cli. Do not edit manually.

//! Pure validation functions for ApiKey DTOs.

use hexforge::ValidationError;

use crate::domain::{CreateApiKey, UpdateApiKey};

/// Validate a CreateApiKey request.
pub fn validate_create_api_key(_input: &CreateApiKey) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}

/// Validate an UpdateApiKey request.
pub fn validate_update_api_key(_input: &UpdateApiKey) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}
