//! Generated by hexforge-cli. Do not edit manually.

//! Pure validation functions for BibItem DTOs.

use hexforge::ValidationError;

use crate::domain::{CreateBibItem, UpdateBibItem};

/// Validate a CreateBibItem request.
pub fn validate_create_bib_item(_input: &CreateBibItem) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}

/// Validate an UpdateBibItem request.
pub fn validate_update_bib_item(_input: &UpdateBibItem) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}
