//! Generated by hexforge-cli. Do not edit manually.

//! Pure validation functions for BibitemNotes DTOs.

use hexforge::ValidationError;

use crate::domain::{CreateBibitemNotes, UpdateBibitemNotes};

/// Validate a CreateBibitemNotes request.
pub fn validate_create_bibitem_notes(_input: &CreateBibitemNotes) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}

/// Validate an UpdateBibitemNotes request.
pub fn validate_update_bibitem_notes(_input: &UpdateBibitemNotes) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}
