//! Generated by hexforge-cli. Do not edit manually.

//! Pure validation functions for DataVersion DTOs.

use hexforge::ValidationError;

use crate::domain::{CreateDataVersion, UpdateDataVersion};

/// Validate a CreateDataVersion request.
pub fn validate_create_data_version(_input: &CreateDataVersion) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}

/// Validate an UpdateDataVersion request.
pub fn validate_update_data_version(_input: &UpdateDataVersion) -> Result<(), ValidationError> {
    // TODO: Add custom validation rules
    Ok(())
}
