//! Generated by hexforge-cli. Do not edit manually.

//! Database enum mappings for domain types.

hexforge::impl_db_enum! {
    crate::domain::AuthorRole => "author_role", rename_all = "lowercase" {
        Author,
        Editor,
        Guesteditor,
    }
}

hexforge::impl_db_enum! {
    crate::domain::EntryType => "entry_type", rename_all = "lowercase" {
        Article,
        Book,
        Incollection,
        Inproceedings,
        Mastersthesis,
        Misc,
        Phdthesis,
        Proceedings,
        Techreport,
        Unpublished,
        Unknown = "UNKNOWN",
    }
}

hexforge::impl_db_enum! {
    crate::domain::Epoch => "epoch", rename_all = "kebab-case" {
        AncientPhilosophy,
        AncientScientists,
        AustrianPhilosophy,
        BritishIdealism,
        Classics,
        Contemporaries,
        ContemporaryScientists,
        ContinentalPhilosophy,
        CriticalTheory,
        Cynics,
        Enlightenment,
        Existentialism,
        ExoticPhilosophy,
        GermanIdealism,
        GermanRationalism,
        GestaltPsychology,
        Hermeneutics,
        IslamicPhilosophy,
        Mathematicians,
        MedievalPhilosophy,
        ModernPhilosophy,
        ModernScientists,
        NeoKantianism,
        Neoplatonism,
        NewRealism,
        OrdinaryLanguagePhilosophy,
        Phenomenology,
        PolishLogic,
        Pragmatism,
        Presocratics,
        Renaissance,
        Stoics,
        Theologians,
        ViennaCircle,
    }
}

hexforge::impl_db_enum! {
    crate::domain::LangId => "langid", rename_all = "lowercase" {
        Catalan,
        Czech,
        Danish,
        Dutch,
        English,
        French,
        German,
        Greek,
        Italian,
        Latin,
        Lithuanian,
        Polish,
        Portuguese,
        Romanian,
        Russian,
        Slovak,
        Spanish,
        Swedish,
        Unknown,
    }
}

hexforge::impl_db_enum! {
    crate::domain::License => "license", rename_all = "kebab-case" {
        CcBy3 = "cc-by-3",
        CcBy4 = "cc-by-4",
        CcBySa3 = "cc-by-sa-3",
        CcBySa4 = "cc-by-sa-4",
        CcByNc3 = "cc-by-nc-3",
        CcByNc4 = "cc-by-nc-4",
        CcByNcSa3 = "cc-by-nc-sa-3",
        CcByNcSa4 = "cc-by-nc-sa-4",
        CcByNd4 = "cc-by-nd-4",
        CcByNcNd4 = "cc-by-nc-nd-4",
        Cc0,
        AllRightsReserved,
    }
}

hexforge::impl_db_enum! {
    crate::domain::PermissionLevel => "permission_level", rename_all = "lowercase" {
        Public,
        Read,
        Write,
        Admin,
    }
}

hexforge::impl_db_enum! {
    crate::domain::PubState => "pubstate", rename_all = "lowercase" {
        Unpub,
        Forthcoming,
        Inwork,
        Submitted,
        Published,
    }
}

hexforge::impl_db_enum! {
    crate::domain::RefType => "ref_type", rename_all = "snake_case" {
        FurtherRef,
        DependsOn,
    }
}
